require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 200

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

convention:Metrics/BlockLength:
  Max: 70
